export const SET_DATA = [
    {
        "SetNameEN": "Holiday Dinner",
        "SetID": "501",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_501.png",
        "Colour": "#6b57db",
        "Raw": "1",
        "SetNameTC": "Holiday Dinner",
        "SetNameSC": "Holiday Dinner"
    },
    {
        "SetNameEN": "Sweater Party",
        "SetID": "502",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_502.png",
        "Colour": "#79dea7",
        "Raw": "1",
        "SetNameTC": "Sweater Party",
        "SetNameSC": "Sweater Party"
    },
    {
        "SetNameEN": "Winter Traditions",
        "SetID": "503",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_503.png",
        "Colour": "#6e30f2",
        "Raw": "1",
        "SetNameTC": "Winter Traditions",
        "SetNameSC": "Winter Traditions"
    },
    {
        "SetNameEN": "Santa's Workshop",
        "SetID": "504",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_504.png",
        "Colour": "#67843f",
        "Raw": "1",
        "SetNameTC": "Santa's Workshop",
        "SetNameSC": "Santa's Workshop"
    },
    {
        "SetNameEN": "Festive Feasts",
        "SetID": "505",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_505.png",
        "Colour": "#2979f2",
        "Raw": "1",
        "SetNameTC": "Festive Feasts",
        "SetNameSC": "Festive Feasts"
    },
    {
        "SetNameEN": "Nutcracker Dreams",
        "SetID": "506",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_506.png",
        "Colour": "#e32f8d",
        "Raw": "1",
        "SetNameTC": "Nutcracker Dreams",
        "SetNameSC": "Nutcracker Dreams"
    },
    {
        "SetNameEN": "Sweet Home",
        "SetID": "507",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_507.png",
        "Colour": "#dc6262",
        "Raw": "1",
        "SetNameTC": "Sweet Home",
        "SetNameSC": "Sweet Home"
    },
    {
        "SetNameEN": "The Perfect Gift",
        "SetID": "508",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_508.png",
        "Colour": "#bd3b3e",
        "Raw": "1",
        "SetNameTC": "The Perfect Gift",
        "SetNameSC": "The Perfect Gift"
    },
    {
        "SetNameEN": "Snowed In",
        "SetID": "509",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_509.png",
        "Colour": "#0d8f61",
        "Raw": "1",
        "SetNameTC": "Snowed In",
        "SetNameSC": "Snowed In"
    },
    {
        "SetNameEN": "Holiday Bakes",
        "SetID": "510",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_510.png",
        "Colour": "#00e2ff",
        "Raw": "1",
        "SetNameTC": "Holiday Bakes",
        "SetNameSC": "Holiday Bakes"
    },
    {
        "SetNameEN": "Outdoor Fun!",
        "SetID": "511",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_511.png",
        "Colour": "#4ebfcd",
        "Raw": "1",
        "SetNameTC": "Outdoor Fun!",
        "SetNameSC": "Outdoor Fun!"
    },
    {
        "SetNameEN": "Monopoly World",
        "SetID": "512",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "0",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_512.png",
        "Colour": "#7844c4",
        "Raw": "1",
        "SetNameTC": "Monopoly World",
        "SetNameSC": "Monopoly World"
    },
    {
        "SetNameEN": "Merry Krampus!",
        "SetID": "513",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "1",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_513.png",
        "Colour": "#3e8fa4",
        "Raw": "1",
        "SetNameTC": "Merry Krampus!",
        "SetNameSC": "Merry Krampus!"
    },
    {
        "SetNameEN": "Australian Xmas",
        "SetID": "514",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "1",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_514.png",
        "Colour": "#e66847",
        "Raw": "1",
        "SetNameTC": "Australian Xmas",
        "SetNameSC": "Australian Xmas"
    },
    {
        "SetNameEN": "Christmas Parade",
        "SetID": "515",
        "AlbumName": "Heartfelt Holidays",
        "AlbumNo": "5",
        "Prestige": "1",
        "StartTime": "1701457200",
        "EndTime": "1704394799",
        "ImageSource": "Icon_515.png",
        "Colour": "#f70f0f",
        "Raw": "1",
        "SetNameTC": "Christmas Parade",
        "SetNameSC": "Christmas Parade"
    },
    {
        "SetNameEN": "Best Beginnings",
        "SetID": "601",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_601.png",
        "Colour": "#e52c45",
        "Raw": "1",
        "SetNameTC": "Best Beginnings",
        "SetNameSC": "Best Beginnings"
    },
    {
        "SetNameEN": "The Top Hat",
        "SetID": "602",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_602.png",
        "Colour": "#7d62ff",
        "Raw": "1",
        "SetNameTC": "The Top Hat",
        "SetNameSC": "The Top Hat"
    },
    {
        "SetNameEN": "Across the Board",
        "SetID": "603",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_603.png",
        "Colour": "#21b1da",
        "Raw": "1",
        "SetNameTC": "Across the Board",
        "SetNameSC": "Across the Board"
    },
    {
        "SetNameEN": "The Battleship",
        "SetID": "604",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_604.png",
        "Colour": "#34bd9e",
        "Raw": "1",
        "SetNameTC": "The Battleship",
        "SetNameSC": "The Battleship"
    },
    {
        "SetNameEN": "On a Roll",
        "SetID": "605",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_605.png",
        "Colour": "#ff8449",
        "Raw": "1",
        "SetNameTC": "On a Roll",
        "SetNameSC": "On a Roll"
    },
    {
        "SetNameEN": "The Thimble",
        "SetID": "606",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_606.png",
        "Colour": "#00b1d3",
        "Raw": "1",
        "SetNameTC": "The Thimble",
        "SetNameSC": "The Thimble"
    },
    {
        "SetNameEN": "Card Quest",
        "SetID": "607",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_607.png",
        "Colour": "#3cbcff",
        "Raw": "1",
        "SetNameTC": "Card Quest",
        "SetNameSC": "Card Quest"
    },
    {
        "SetNameEN": "The Iron",
        "SetID": "608",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_608.png",
        "Colour": "#1fc4e6",
        "Raw": "1",
        "SetNameTC": "The Iron",
        "SetNameSC": "The Iron"
    },
    {
        "SetNameEN": "Maximum Occupancy",
        "SetID": "609",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_609.png",
        "Colour": "#00b8a0",
        "Raw": "1",
        "SetNameTC": "Maximum Occupancy",
        "SetNameSC": "Maximum Occupancy"
    },
    {
        "SetNameEN": "The Boot",
        "SetID": "610",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_610.png",
        "Colour": "#9246d3",
        "Raw": "1",
        "SetNameTC": "The Boot",
        "SetNameSC": "The Boot"
    },
    {
        "SetNameEN": "Utility Fun",
        "SetID": "611",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_611.png",
        "Colour": "#eb407d",
        "Raw": "1",
        "SetNameTC": "Utility Fun",
        "SetNameSC": "Utility Fun"
    },
    {
        "SetNameEN": "The Cannon",
        "SetID": "612",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_612.png",
        "Colour": "#ed758f",
        "Raw": "1",
        "SetNameTC": "The Cannon",
        "SetNameSC": "The Cannon"
    },
    {
        "SetNameEN": "Free Parking",
        "SetID": "613",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_613.png",
        "Colour": "#df7015",
        "Raw": "1",
        "SetNameTC": "Free Parking",
        "SetNameSC": "Free Parking"
    },
    {
        "SetNameEN": "Railroad Tycoon",
        "SetID": "614",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_614.png",
        "Colour": "#db8b20",
        "Raw": "1",
        "SetNameTC": "Railroad Tycoon",
        "SetNameSC": "Railroad Tycoon"
    },
    {
        "SetNameEN": "Tokenmania",
        "SetID": "615",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_615.png",
        "Colour": "#ffa400",
        "Raw": "1",
        "SetNameTC": "Tokenmania",
        "SetNameSC": "Tokenmania"
    },
    {
        "SetNameEN": "Launch Day!",
        "SetID": "616",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_616.png",
        "Colour": "#df7879",
        "Raw": "1",
        "SetNameTC": "Launch Day!",
        "SetNameSC": "Launch Day!"
    },
    {
        "SetNameEN": "Fever!",
        "SetID": "617",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_617.png",
        "Colour": "#dbad79",
        "Raw": "1",
        "SetNameTC": "Fever!",
        "SetNameSC": "Fever!"
    },
    {
        "SetNameEN": "Doggopoly",
        "SetID": "618",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_618.png",
        "Colour": "#71d3d2",
        "Raw": "1",
        "SetNameTC": "Doggopoly",
        "SetNameSC": "Doggopoly"
    },
    {
        "SetNameEN": "Game Awards",
        "SetID": "619",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_619.png",
        "Colour": "#ab58fd",
        "Raw": "1",
        "SetNameTC": "Game Awards",
        "SetNameSC": "Game Awards"
    },
    {
        "SetNameEN": "Ms Monopoly",
        "SetID": "620",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_620.png",
        "Colour": "#ff73af",
        "Raw": "1",
        "SetNameTC": "Ms Monopoly",
        "SetNameSC": "Ms Monopoly"
    },
    {
        "SetNameEN": "Go!",
        "SetID": "621",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "0",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_621.png",
        "Colour": "#df4320",
        "Raw": "1",
        "SetNameTC": "Go!",
        "SetNameSC": "Go!"
    },
    {
        "SetNameEN": "The Racecar",
        "SetID": "622",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "1",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_622.png",
        "Colour": "#4399e5",
        "Raw": "1",
        "SetNameTC": "The Racecar",
        "SetNameSC": "The Racecar"
    },
    {
        "SetNameEN": "Monopoly VR",
        "SetID": "623",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "1",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_623.png",
        "Colour": "#c83edf",
        "Raw": "1",
        "SetNameTC": "Monopoly VR",
        "SetNameSC": "Monopoly VR"
    },
    {
        "SetNameEN": "Monopoly Moments",
        "SetID": "624",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "1",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_624.png",
        "Colour": "#8c67d8",
        "Raw": "1",
        "SetNameTC": "Monopoly Moments",
        "SetNameSC": "Monopoly Moments"
    },
    {
        "SetNameEN": "Money Tree",
        "SetID": "625",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "1",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_625.png",
        "Colour": "#ad31e9",
        "Raw": "1",
        "SetNameTC": "Money Tree",
        "SetNameSC": "Money Tree"
    },
    {
        "SetNameEN": "The Rubber Ducky",
        "SetID": "626",
        "AlbumName": "Monopoly Origins",
        "AlbumNo": "6",
        "Prestige": "1",
        "StartTime": "1704394799",
        "EndTime": "1711652400",
        "ImageSource": "Icon_626.png",
        "Colour": "#54b8cc",
        "Raw": "1",
        "SetNameTC": "The Rubber Ducky",
        "SetNameSC": "The Rubber Ducky"
    },
    {
        "SetNameEN": "Symphony Store",
        "SetID": "701",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_701.png",
        "Colour": "#e8b04d",
        "Raw": "1",
        "SetNameTC": "交響曲商店",
        "SetNameSC": "交响曲商店"
    },
    {
        "SetNameEN": "Musical Memoir",
        "SetID": "702",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_702.png",
        "Colour": "#7963ce",
        "Raw": "1",
        "SetNameTC": "音樂回憶錄",
        "SetNameSC": "音乐回忆录"
    },
    {
        "SetNameEN": "Swingin' Notes",
        "SetID": "703",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_703.png",
        "Colour": "#cd56b4",
        "Raw": "1",
        "SetNameTC": "搖擺音符",
        "SetNameSC": "摇摆音符"
    },
    {
        "SetNameEN": "Ludwig Van Monopoly",
        "SetID": "704",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_704.png",
        "Colour": "#67b1aa",
        "Raw": "1",
        "SetNameTC": "路德維希‧范‧大富翁",
        "SetNameSC": "路德维希‧范‧大富翁"
    },
    {
        "SetNameEN": "Musical Bonds",
        "SetID": "705",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_705.png",
        "Colour": "#f84b62",
        "Raw": "1",
        "SetNameTC": "音樂紐帶",
        "SetNameSC": "音乐纽带"
    },
    {
        "SetNameEN": "World Music",
        "SetID": "706",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_706.png",
        "Colour": "#8522ec",
        "Raw": "1",
        "SetNameTC": "世界音樂",
        "SetNameSC": "世界音乐"
    },
    {
        "SetNameEN": "Boy Band",
        "SetID": "707",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_707.png",
        "Colour": "#04cfdc",
        "Raw": "1",
        "SetNameTC": "男孩樂團",
        "SetNameSC": "男孩乐团"
    },
    {
        "SetNameEN": "Crescendo Academy",
        "SetID": "708",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_708.png",
        "Colour": "#839b0a",
        "Raw": "1",
        "SetNameTC": "頂尖音樂學院",
        "SetNameSC": "顶尖音乐学院"
    },
    {
        "SetNameEN": "Karaoke Night",
        "SetID": "709",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_709.png",
        "Colour": "#dc21a4",
        "Raw": "1",
        "SetNameTC": "卡拉OK之夜",
        "SetNameSC": "卡拉OK之夜"
    },
    {
        "SetNameEN": "Country Roads",
        "SetID": "710",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_710.png",
        "Colour": "#babe5f",
        "Raw": "1",
        "SetNameTC": "鄉村小路",
        "SetNameSC": "乡村小路"
    },
    {
        "SetNameEN": "Mr Mozart",
        "SetID": "711",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_711.png",
        "Colour": "#e17559",
        "Raw": "1",
        "SetNameTC": "莫札特先生",
        "SetNameSC": "莫扎特先生"
    },
    {
        "SetNameEN": "Pop Princess",
        "SetID": "712",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_712.png",
        "Colour": "#ba83fb",
        "Raw": "1",
        "SetNameTC": "流行公主",
        "SetNameSC": "流行公主"
    },
    {
        "SetNameEN": "Music Festival",
        "SetID": "713",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_713.png",
        "Colour": "#edb046",
        "Raw": "1",
        "SetNameTC": "音樂節",
        "SetNameSC": "音乐节"
    },
    {
        "SetNameEN": "Spin City",
        "SetID": "714",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_714.png",
        "Colour": "#f76961",
        "Raw": "1",
        "SetNameTC": "唱片之城",
        "SetNameSC": "唱片之城"
    },
    {
        "SetNameEN": "Everyday Tunes",
        "SetID": "715",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_715.png",
        "Colour": "#f05077",
        "Raw": "1",
        "SetNameTC": "日常小調",
        "SetNameSC": "日常小调"
    },
    {
        "SetNameEN": "K-Pop Idols",
        "SetID": "716",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_716.png",
        "Colour": "#fd5365",
        "Raw": "1",
        "SetNameTC": "K-POP偶像",
        "SetNameSC": "K-POP偶像"
    },
    {
        "SetNameEN": "Wild Melodies",
        "SetID": "717",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_717.png",
        "Colour": "#b0c876",
        "Raw": "1",
        "SetNameTC": "狂野旋律",
        "SetNameSC": "狂野旋律"
    },
    {
        "SetNameEN": "Disco Time",
        "SetID": "718",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_718.png",
        "Colour": "#e180c3",
        "Raw": "1",
        "SetNameTC": "迪斯可時間",
        "SetNameSC": "迪斯科时间"
    },
    {
        "SetNameEN": "Rockstar Dreams",
        "SetID": "719",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_719.png",
        "Colour": "#7bb096",
        "Raw": "1",
        "SetNameTC": "搖滾巨星之夢",
        "SetNameSC": "摇滚巨星之梦"
    },
    {
        "SetNameEN": "Hip Hop",
        "SetID": "720",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_720.png",
        "Colour": "#b5bd4f",
        "Raw": "1",
        "SetNameTC": "嘻哈",
        "SetNameSC": "嘻哈"
    },
    {
        "SetNameEN": "Bel Canto",
        "SetID": "721",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "0",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_721.png",
        "Colour": "#bd8dd2",
        "Raw": "1",
        "SetNameTC": "美聲",
        "SetNameSC": "美声"
    },
    {
        "SetNameEN": "Electronic Beats",
        "SetID": "722",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "1",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_722.png",
        "Colour": "#cf85c7",
        "Raw": "1",
        "SetNameTC": "電子節拍",
        "SetNameSC": "电子节拍"
    },
    {
        "SetNameEN": "On Tour!",
        "SetID": "723",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "1",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_723.png",
        "Colour": "#ae8bc1",
        "Raw": "1",
        "SetNameTC": "巡迴演出！",
        "SetNameSC": "巡回演出！"
    },
    {
        "SetNameEN": "Olé",
        "SetID": "724",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "1",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_724.png",
        "Colour": "#f2d56d",
        "Raw": "1",
        "SetNameTC": "噢嘞西班牙",
        "SetNameSC": "噢嘞西班牙"
    },
    {
        "SetNameEN": "Primal Groove",
        "SetID": "725",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "1",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_725.png",
        "Colour": "#73c9ed",
        "Raw": "1",
        "SetNameTC": "原始律動",
        "SetNameSC": "原始律动"
    },
    {
        "SetNameEN": "The Moguls",
        "SetID": "726",
        "AlbumName": "Making Music",
        "AlbumNo": "7",
        "Prestige": "1",
        "StartTime": "1711652401",
        "EndTime": "1718909999",
        "ImageSource": "Icon_726.png",
        "Colour": "#ef4b0a",
        "Raw": "1",
        "SetNameTC": "大亨樂團",
        "SetNameSC": "大亨乐团"
    },
    {
        "SetNameEN": "Opening Ceremony",
        "SetID": "801",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_801.png",
        "Colour": "#a666e7",
        "Raw": "1",
        "SetNameTC": "開幕典禮",
        "SetNameSC": "开幕典礼"
    },
    {
        "SetNameEN": "Shield Breaker",
        "SetID": "802",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_802.png",
        "Colour": "#84c9f2",
        "Raw": "1",
        "SetNameTC": "護盾破壞者",
        "SetNameSC": "护盾破坏者"
    },
    {
        "SetNameEN": "Rowing",
        "SetID": "803",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_803.png",
        "Colour": "#55a5c3",
        "Raw": "1",
        "SetNameTC": "划船",
        "SetNameSC": "划船"
    },
    {
        "SetNameEN": "Swimming",
        "SetID": "804",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_804.png",
        "Colour": "#ff8330",
        "Raw": "1",
        "SetNameTC": "游泳",
        "SetNameSC": "游泳"
    },
    {
        "SetNameEN": "Wheelchair Rugby",
        "SetID": "805",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_805.png",
        "Colour": "#f0607e",
        "Raw": "1",
        "SetNameTC": "輪椅橄欖球",
        "SetNameSC": "轮椅橄榄球"
    },
    {
        "SetNameEN": "Caber Tossing",
        "SetID": "806",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_806.png",
        "Colour": "#b16621",
        "Raw": "1",
        "SetNameTC": "擲柱",
        "SetNameSC": "掷柱"
    },
    {
        "SetNameEN": "Throw Put",
        "SetID": "807",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_807.png",
        "Colour": "#fbb324",
        "Raw": "1",
        "SetNameTC": "投擲推杆",
        "SetNameSC": "投掷推杆"
    },
    {
        "SetNameEN": "On Target",
        "SetID": "808",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_808.png",
        "Colour": "#3889e3",
        "Raw": "1",
        "SetNameTC": "射擊",
        "SetNameSC": "射击"
    },
    {
        "SetNameEN": "Hockey",
        "SetID": "809",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_809.png",
        "Colour": "#61c35d",
        "Raw": "1",
        "SetNameTC": "曲棍球",
        "SetNameSC": "曲棍球"
    },
    {
        "SetNameEN": "Skateboarding",
        "SetID": "810",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_810.png",
        "Colour": "#ff77bb",
        "Raw": "1",
        "SetNameTC": "滑板運動",
        "SetNameSC": "滑板运动"
    },
    {
        "SetNameEN": "Gymnastics",
        "SetID": "811",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_811.png",
        "Colour": "#e6afe6",
        "Raw": "1",
        "SetNameTC": "體操",
        "SetNameSC": "体操"
    },
    {
        "SetNameEN": "Dice Lifting",
        "SetID": "812",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_812.png",
        "Colour": "#423ad7",
        "Raw": "1",
        "SetNameTC": "骰子舉重",
        "SetNameSC": "骰子举重"
    },
    {
        "SetNameEN": "Railroad Racing",
        "SetID": "813",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_813.png",
        "Colour": "#4bc653",
        "Raw": "1",
        "SetNameTC": "鐵路競賽",
        "SetNameSC": "铁路竞赛"
    },
    {
        "SetNameEN": "Ping Pong",
        "SetID": "814",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_814.png",
        "Colour": "#ff8165",
        "Raw": "1",
        "SetNameTC": "乒乓球",
        "SetNameSC": "乒乓球"
    },
    {
        "SetNameEN": "Diving",
        "SetID": "815",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_815.png",
        "Colour": "#76d6c7",
        "Raw": "1",
        "SetNameTC": "跳水",
        "SetNameSC": "跳水"
    },
    {
        "SetNameEN": "Archery",
        "SetID": "816",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_816.png",
        "Colour": "#ebb751",
        "Raw": "1",
        "SetNameTC": "射箭",
        "SetNameSC": "射箭"
    },
    {
        "SetNameEN": "Surfing",
        "SetID": "817",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_817.png",
        "Colour": "#0baec5",
        "Raw": "1",
        "SetNameTC": "衝浪",
        "SetNameSC": "冲浪"
    },
    {
        "SetNameEN": "Parallel Parking",
        "SetID": "818",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_818.png",
        "Colour": "#b53d32",
        "Raw": "1",
        "SetNameTC": "水平泊車",
        "SetNameSC": "水平泊车"
    },
    {
        "SetNameEN": "Wheelbarrow Race",
        "SetID": "819",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_819.png",
        "Colour": "#e58539",
        "Raw": "1",
        "SetNameTC": "獨輪車競賽",
        "SetNameSC": "独轮车竞赛"
    },
    {
        "SetNameEN": "Remote Duck Races",
        "SetID": "820",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_820.png",
        "Colour": "#e7b149",
        "Raw": "1",
        "SetNameTC": "遠距鴨賽",
        "SetNameSC": "远距鸭赛"
    },
    {
        "SetNameEN": "Baseball",
        "SetID": "821",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_821.png",
        "Colour": "#d97f13",
        "Raw": "1",
        "SetNameTC": "棒球",
        "SetNameSC": "棒球"
    },
    {
        "SetNameEN": "Fencing",
        "SetID": "822",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_822.png",
        "Colour": "#6061ab",
        "Raw": "1",
        "SetNameTC": "擊劍",
        "SetNameSC": "击剑"
    },
    {
        "SetNameEN": "Shopping Spree",
        "SetID": "823",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "0",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_823.png",
        "Colour": "#eb7b87",
        "Raw": "1",
        "SetNameTC": "瘋狂購物",
        "SetNameSC": "疯狂购物"
    },
    {
        "SetNameEN": "Climbing",
        "SetID": "824",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "1",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_824.png",
        "Colour": "#8e6fb8",
        "Raw": "1",
        "SetNameTC": "攀岩",
        "SetNameSC": "攀岩"
    },
    {
        "SetNameEN": "Hot Air Balloon Race",
        "SetID": "825",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "1",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_825.png",
        "Colour": "#75cfc0",
        "Raw": "1",
        "SetNameTC": "熱氣球競賽",
        "SetNameSC": "热气球竞赛"
    },
    {
        "SetNameEN": "Triathlon",
        "SetID": "826",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "1",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_826.png",
        "Colour": "#f5bb3d",
        "Raw": "1",
        "SetNameTC": "鐵人三項",
        "SetNameSC": "铁人三项"
    },
    {
        "SetNameEN": "Soccer",
        "SetID": "827",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "1",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_827.png",
        "Colour": "#2fab4b",
        "Raw": "1",
        "SetNameTC": "足球",
        "SetNameSC": "足球"
    },
    {
        "SetNameEN": "Cycling",
        "SetID": "828",
        "AlbumName": "Monopoly Games",
        "AlbumNo": "8",
        "Prestige": "1",
        "StartTime": "1718910000",
        "EndTime": "1727377199",
        "ImageSource": "Icon_828.png",
        "Colour": "#5560DB",
        "Raw": "1",
        "SetNameTC": "單車",
        "SetNameSC": "单车"
    }
]